### ISSUE TITLE
Missing Robin sprite

### ISSUE THREAD

**Issue by victorfeight** [Theawesomeboophis/UndeadPeopleTileset#10]
Missing sprite for mon_robin, currently shows up as V

**Comment by Theawesomeboophis** [comment]
Thanks for submitting an issue, I'll definitely try to get this in the next update after I update unpacked, as it seems to not be up to date with the packed version. I have a lot of sprites from various sources that I plan to add in the update after I fix unpacked.

**Comment by TheLyca0n** [comment]
Cunning Feral is also missing

**Comment by Theawesomeboophis** [comment]
That is one of the new ferals from latest experimental right? I'll add it to the list of things to do for the next tileset update ( update's probably gonna be huge when finished, it might take a while, although I think bulk updates instead of small sprite updates will work better in the long run). Thank you for notifying me.

**Comment by TheLyca0n** [comment]
Don't envy the amount of work considering the additions in the portal storms and whatnot, regardless you are a saint dude. You accept donations

**Comment by Theawesomeboophis** [comment]
No donations. I just do it because it's what I like to do.

**Comment by Stephen2** [comment]
ty @Theawesomeboophis your are truly the most awesome of all boophis

**Comment by victorfeight** [comment]
ty @Theawesomeboophis your sprite packs make the game so immersive and I gotta get back into it!

**Comment by Theawesomeboophis** [comment]
The sprites are made by members of the Discord, but thank you for downloading the tileset.
