### ISSUE TITLE
Graphical Overmap Issues

### ISSUE THREAD

**Issue by ImperatorTitanius** [Theawesomeboophis/UndeadPeopleTileset#70]
Just reinstalled UDP and set it up as usual, placed the tileset into C:\Users\[my account]\Documents\CDDA\dda\userdata\gfx. Got this when I turned on UDP as my overmap tiles.

![image](https://user-images.githubusercontent.com/124532767/216848082-856c0d0f-76a8-41ea-9327-0f90a701e995.png)

All open air map tiles become a mix of the Quadruped and a dragon texture for some reason. Doesn't apply to all open air tiles period, as the crater I made from a mininuke didn't show it with the normal tiles.
Has anyone encountered a similar issue before? If so, are there any known fixes?
I've done a clean reinstall of CDDA twice now and tried it with the tiles, still got the same issue each time.

**Comment by Xayrlen** [comment]
Not only that, but there is a problem with layers. If you have mutations changing your eyes, the original color choice will clip through it.
![1234](https://user-images.githubusercontent.com/86978521/216963031-4b7e6b05-e4dd-4553-b9ce-8d61da184334.png)

Additionally, some places on the map are obviously sticking out of the landscape. And map extras are having this "tileset error" tiles instead of an old "&" symbol.
![12345](https://user-images.githubusercontent.com/86978521/216963485-f1de6c89-1551-4c77-b575-4eae959c9f66.png)

**Comment by Lippiece** [comment]
@Theawesomeboophis 
I've replaced the old `MSX++UnDeadPeopleEdition` with the current from the repo. There are no more dragons, but autonotes are still broken. Maybe I've installed it incorrectly?

<details>
<summary>Screenshot</summary>

![cataclysm-tiles_JTU4OxesTi](https://user-images.githubusercontent.com/47634624/217868813-a6c932b1-0bc4-4487-afd8-fbfd1889cc5a.png)


</details>

**Comment by zakhad** [comment]
Same for me i also get auto note errors 
![image](https://user-images.githubusercontent.com/5264667/218183659-d77c001e-304b-46fa-874f-4046241633d8.png)
