### ISSUE TITLE
About contribution on the tileset.

### ISSUE THREAD

**Issue by adamdeno** [Theawesomeboophis/UndeadPeopleTileset#9]
Hello there , i was wondering if i can help in pushing out textures for un-textured stuff?

the reason for this is because of long period of time without receiving any textures for the new stuff thats being added.

anyone who might want to help too anytime in the future , are we allowed to contribute to the tileset too?

if so and for those who are new aswell , what should we play with when we texture stuff?

thanks for your effort and time.

**Comment by Theawesomeboophis** [comment]
Yes, all contributions are welcome, anyone can contribute as long as they submit PRs to one of these two forks:
Firestorm01X2
/
UndeadPeopleUnpacked
Theawesomeboophis
/
UndeadPeopleUnpacked
Preferably the second fork, so that way my colloborators can review it and fix it, and then I can put the packed files here.

**Comment by adamdeno** [comment]
Alright thanks for letting me and those in the future know!
